### ISSUE TITLE
Access right bad

### ISSUE THREAD

**Issue by mrlove** [whitneyit/galen-jar#2]
Hi,

we need the access right "chmod 0700" for the executable bash script "./node_modules/galen-jar/galen"

Can you provide an update? If you want i can make an pull request, but i guess it is not a big deal for you.

Best from Germany.

**Comment by alwin-rewedigital** [comment]
For example:

package.json
```
{
  "name": "foo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "galen-jar": "^1.6.3"
  }
}
```

when you now run `npm install`
then you'll see:
```
ls -la node_modules/galen-jar/galen
-rw-rw-r-- 1 user user 564 Jun  1 12:49 node_modules/galen-jar/galen
```

the funny thing is, that `git clone git@github.com:whitneyit/galen-jar.git` will set the rights correctly:

```
ls -la galen 
-rwxrwxr-x 1 user user 564 Jun  1 14:57 galen
```

**Comment by whitneyit** [comment]
The file stat is marked as `755`. Is that not good enough? Git repos can onl track `644` or `755`

**Comment by alwin-rewedigital** [comment]
yes it seems to be a npm issue somehow

**Comment by whitneyit** [comment]
Use

```json
  "devDependencies": {
    "galen-jar": "whitneyit/galen-jar"
  }
```

That's the GitHub shorthand

**Comment by alwin-rewedigital** [comment]
what speaks againts marking that file as binary?:
https://docs.npmjs.com/files/package.json#bin

**Comment by whitneyit** [comment]
That's what I'm hoping to do with the `galen-cli` repo
